"""Insight models and persistence for the proactive agent."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional


def utc_now() -> datetime:
    """Get current UTC time as a timezone-aware datetime."""
    return datetime.now(timezone.utc)


class InsightType(Enum):
    """Types of proactive insights generated by the agent."""

    CONTRADICTION = "contradiction"
    HIDDEN_CONNECTION = "hidden_connection"
    REMINDER = "reminder"


@dataclass
class Insight:
    """A single actionable observation produced from graph analysis."""

    insight_type: InsightType
    title: str
    description: str
    node_ids: list[str] = field(default_factory=list)
    edge_ids: list[str] = field(default_factory=list)
    score: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=utc_now)

    def __post_init__(self) -> None:
        if isinstance(self.insight_type, str):
            self.insight_type = InsightType(self.insight_type)

    def to_dict(self) -> dict[str, Any]:
        """Serialize an insight to a JSON-compatible dictionary."""
        return {
            "id": self.id,
            "insight_type": self.insight_type.value,
            "title": self.title,
            "description": self.description,
            "node_ids": self.node_ids,
            "edge_ids": self.edge_ids,
            "score": self.score,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Insight":
        """Deserialize an insight from a dictionary."""
        values = data.copy()
        values["insight_type"] = InsightType(values["insight_type"])
        values["created_at"] = datetime.fromisoformat(values["created_at"])
        return cls(**values)


@dataclass
class Digest:
    """A short digest with the most relevant proactive insights."""

    insights: list[Insight] = field(default_factory=list)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=utc_now)

    def to_dict(self) -> dict[str, Any]:
        """Serialize a digest to a JSON-compatible dictionary."""
        return {
            "id": self.id,
            "created_at": self.created_at.isoformat(),
            "insights": [insight.to_dict() for insight in self.insights],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Digest":
        """Deserialize a digest from a dictionary."""
        return cls(
            id=data["id"],
            created_at=datetime.fromisoformat(data["created_at"]),
            insights=[Insight.from_dict(item) for item in data.get("insights", [])],
        )

    def format_text(self) -> str:
        """Render a compact human-readable digest."""
        if not self.insights:
            return "Проактивные инсайты не найдены."

        lines = [f"Дайджест {self.id}"]
        for index, insight in enumerate(self.insights, start=1):
            lines.append(
                f"{index}. [{insight.insight_type.value}] {insight.title} "
                f"(score={insight.score:.3f})"
            )
            lines.append(f"   {insight.description}")
            statement_a = insight.metadata.get("statement_a")
            statement_b = insight.metadata.get("statement_b")
            if insight.insight_type == InsightType.CONTRADICTION and statement_a and statement_b:
                label_a, label_b = self._statement_labels(statement_a, statement_b)
                lines.append(f"   {label_a}: {self._compact(statement_a)}")
                lines.append(f"   {label_b}: {self._compact(statement_b)}")
        return "\n".join(lines)

    def _statement_labels(self, statement_a: Any, statement_b: Any) -> tuple[str, str]:
        return "Утверждение A", "Утверждение B"

    def _looks_cyrillic(self, text: str) -> bool:
        letters = [char for char in text if char.isalpha()]
        if not letters:
            return False
        cyrillic = sum(1 for char in letters if "\u0400" <= char <= "\u04ff")
        return cyrillic / len(letters) >= 0.3

    def _compact(self, value: Any, limit: int = 240) -> str:
        text = " ".join(str(value).split())
        return text if len(text) <= limit else f"{text[: limit - 3]}..."


class InsightStore:
    """Persist digests generated by the proactive agent as JSON."""

    def __init__(self, storage_path: Optional[str | Path]) -> None:
        self.storage_path = Path(storage_path).with_suffix(".insights.json") if storage_path else None

    def save_digest(self, digest: Digest) -> None:
        """Append a digest to persistent storage."""
        if not self.storage_path:
            return

        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        digests = self.load_digests()
        digests.append(digest)
        with open(self.storage_path, "w", encoding="utf-8") as file:
            json.dump([item.to_dict() for item in digests], file, ensure_ascii=False, indent=2)

    def load_digests(self) -> list[Digest]:
        """Load all saved digests."""
        if not self.storage_path or not self.storage_path.exists():
            return []

        with open(self.storage_path, "r", encoding="utf-8") as file:
            data = json.load(file)
        return [Digest.from_dict(item) for item in data]

    def get_latest_digest(self) -> Optional[Digest]:
        """Return the newest saved digest, if any."""
        digests = self.load_digests()
        return digests[-1] if digests else None
